apiVersion: epicconstructions.com/v1alpha1
kind: CronJob
metadata:
  name: southwest-alerts
  namespace: default
  build: "BUILD_NUMBER"
spec:
  schedule: "5 14 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: registry.gitlab.com
          restartPolicy: OnFailure
          containers:
          - image: registry.gitlab.com/tdickman/southwest-alerts:buildBUILD_NUMBER
            name: southwest-alerts
            env:
            - name: USERNAME1
              valueFrom:
                secretKeyRef:
                  name: southwest-logins
                  key: username1
            - name: PASSWORD1
              valueFrom:
                secretKeyRef:
                  name: southwest-logins
                  key: password1
            - name: EMAIL1
              valueFrom:
                secretKeyRef:
                  name: southwest-logins
                  key: email1
            - name: MAILGUN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: southwest-logins
                  key: mailgun_api_key
